language: node_js
node_js:
    - "6"
notifications:
    webhooks: https://ohager-hirouter.getbadges.io/api/app/webhook/a3be7bc9-46ad-4fff-8763-b11724f52eac
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
  - node_modules
after-success:
  - bash <(curl -s https://codecov.io/bash)